### ISSUE TITLE
Proper way of adding the flame_forge2d dependency

### ISSUE THREAD

**Issue by osharaki** [flame-engine/flame_box2d#16]
Right now, it doesn't seem flame_forge2d has been published to pub.dev. Should I simply clone this repo into my project and reference via relative path in *pubspec.yaml*? Something like
```
dependencies:
  flutter:
    sdk: flutter
  flame_forge2d:
    path: flame_forge2d
```
