### ISSUE TITLE
Error importing viewport

### ISSUE THREAD

**Issue by jeevanson-vivriti** [flame-engine/flame_box2d#33]
The latest version 0.6.4-rc4 is not compatible with the latest flame 1.0.0-rc8. Getting the following error,

Error: 'Viewport' is imported from both 'package:flame/src/game/viewport.dart' and 'package:flame_forge2d/viewport.dart'.
import 'viewport.dart';

Error: Method not found: 'SpriteComponent.fromSprite'.
  ) : super(SpriteComponent.fromSprite(spriteSize, sprite), spriteSize);

**Comment by erickzanardo** [comment]
There is a PR addressing that already #32

**Comment by leeflix** [comment]
Is there a way to use ```flame_forge2d``` until #32 lands?

**Comment by spydon** [comment]
@felithium you'd have to use one of the early versions of the flame release candidates then.
Try for example: flame_forge2d 0.6.0-rc2 with flame 1.0.0-rc5

Trying to sort this out as soon as possible!

**Comment by dynamicbutter** [comment]
@felithium I got it to work by referring to PR #32's hash in my pubspec like so ...
```yaml
dependencies:
  flame: "1.0.0-rc10"
  flame_forge2d:
    git:
      url: "https://github.com/flame-engine/flame_forge2d.git"
      ref: "ebd4890"
...
```
